/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wts.roms.model;

import java.awt.Component;
import java.beans.Customizer;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.Iterator;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Logger;

/**
 *
 * @author William.Stockhausen
 */
public class CriticalGrid2DVariablesInfoCustomizer extends javax.swing.JPanel
                                             implements Customizer, PropertyChangeListener {

    private static final Logger logger = Logger.getLogger(CriticalGrid2DVariablesInfoCustomizer.class.getName());
    
    /** the object on which to set/get properties */
    private CriticalGrid2DVariablesInfo obj = null;
    /** ROMS GlobalInfo instance */
    private final GlobalInfo romsGI;
    /**
     * Creates new form Grid2DVariablesInfoCustomizer
     */
    public CriticalGrid2DVariablesInfoCustomizer() {
        romsGI = GlobalInfo.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPanel3 = new javax.swing.JPanel();
        jspVariables = new javax.swing.JScrollPane();
        jpVariables = new javax.swing.JPanel();
        cviCustomizer = new wts.roms.model.CriticalVariableInfoCustomizer();
        jPanel1 = new javax.swing.JPanel();
        jcbROMSvariables = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jpPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CriticalGrid2DVariablesInfoCustomizer.class, "CriticalGrid2DVariablesInfoCustomizer.jpPanel3.border.title"))); // NOI18N

        jpVariables.setLayout(new java.awt.GridLayout(0, 1));

        cviCustomizer.setEnabled(false);
        jpVariables.add(cviCustomizer);

        jspVariables.setViewportView(jpVariables);

        javax.swing.GroupLayout jpPanel3Layout = new javax.swing.GroupLayout(jpPanel3);
        jpPanel3.setLayout(jpPanel3Layout);
        jpPanel3Layout.setHorizontalGroup(
            jpPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspVariables, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        jpPanel3Layout.setVerticalGroup(
            jpPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspVariables)
        );

        add(jpPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CriticalGrid2DVariablesInfoCustomizer.class, "CriticalGrid2DVariablesInfoCustomizer.jPanel1.border.title"))); // NOI18N

        jcbROMSvariables.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcbROMSvariables, 0, 638, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcbROMSvariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected wts.roms.model.CriticalVariableInfoCustomizer cviCustomizer;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JComboBox jcbROMSvariables;
    protected javax.swing.JPanel jpPanel3;
    protected javax.swing.JPanel jpVariables;
    protected javax.swing.JScrollPane jspVariables;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Sets the object to be customized in the customizer. Must be a 
     * CriticalGrid2DVariablesInfo instance.
     * 
     * @param bean 
     */
    @Override
    public void setObject(Object bean) {
        if (bean instanceof CriticalGrid2DVariablesInfo){
            obj = (CriticalGrid2DVariablesInfo) bean;
            setObject();
        }
    }

    private void setObject(){
        logger.info("starting SetObject()");
        obj.removePropertyChangeListener(this);
        jpVariables.removeAll();//remove all ovi customizers
        jpVariables.add(cviCustomizer);//this functions as a header
        Set<String> names = obj.getNames();
        for (String name: names){
            logger.info("Found grid2D variable "+name);
            CriticalVariableInfo cvi = obj.getVariableInfo(name);
            CriticalVariableInfoCustomizer cvic = new CriticalVariableInfoCustomizer();
            cvic.setObject(cvi);
            jpVariables.add(cvic);
        }
        setROMSVariables();
        setEnabled(!romsGI.getGridFile().equals(GlobalInfo.PROP_NotSet));
        setVisible(!romsGI.getGridFile().equals(GlobalInfo.PROP_NotSet));
        validate();
        repaint();
        obj.addPropertyChangeListener(this);
        logger.info("finished SetObject()");
    }

    /**
     * Enable/disable all sub-components
     * @param b 
     */
    @Override
    public void setEnabled(boolean b){
        super.setEnabled(b);
        Component[] comps = getComponents();
        for (Component c: comps){
            c.setEnabled(b);
        }
    }
    
    /**
     * Sets the variable names listed in jcbROMSvariables by reading them from the
     * grid file given in the GlobalInfo singleton.
     */
    private void setROMSVariables(){
        jcbROMSvariables.removeAllItems();
        if (!romsGI.getGridFile().equals(GlobalInfo.PROP_NotSet)){
            try {
                NetcdfReader nR = new NetcdfReader(romsGI.getGridFile());
                String[] romsNames = nR.getVariableNames();
                Set<String> names = new TreeSet<>();
                for (String romsName: romsNames) names.add(romsName);
                Iterator<String> it = names.iterator();
                while (it.hasNext()) jcbROMSvariables.addItem(it.next());
            } catch (IOException ex) {
                logger.severe(ex.getLocalizedMessage());
            }
        }
    }
    
    /**
     * Method reacts to changes in the ROMS grid file property of the GlobalInfo singleton
     * by forcing an update of the ROMS variables listed in jcbROMSvariables.
     * 
     * @param evt - a ProertyChange event
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
//        logger.info("PropertyChange: "+evt.toString());
        if (evt.getPropertyName().equals(GlobalInfo.PROP_GridFile)){
            logger.info("PropertyChange: "+evt.toString());
            setObject();//reset object
        } else if (evt.getPropertyName().equals(CriticalGrid2DVariablesInfo.PROP_RESET)){
            logger.info("PropertyChange: "+evt.toString());
            setObject();//reset object
        }
    }
}
