/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wts.models.DisMELS.IBMFunctions.Movement;

import wts.models.DisMELS.framework.IBMFunctions.IBMParameterDouble;

/**
 *
 * @author William.Stockhausen
 */
public class VerticalMovement_FixedDepthAndTempRangeCustomizer extends javax.swing.JPanel implements java.beans.Customizer {
    
    private VerticalMovement_FixedDepthAndTempRange obj = null;;

    /**
     * Creates new customizer DielVerticalMigration_FixedDepthAndTempRangesCustomizer
     */
    public VerticalMovement_FixedDepthAndTempRangeCustomizer() {
        initComponents();
    }
    
    @Override
    public void setObject(Object bean) {
        if (bean instanceof VerticalMovement_FixedDepthAndTempRange){
            obj = (VerticalMovement_FixedDepthAndTempRange) bean;
            setParameters();
        }
    }

    private void setParameters() {
        jtfMinDepth.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthAndTempRange.PARAM_minDepth)).getValueAsString());
        jtfMaxDepth.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthAndTempRange.PARAM_maxDepth)).getValueAsString());
        jtfMinDistOffBottom.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthAndTempRange.PARAM_minDistOffBottom)).getValueAsString());
        jtfMinTemp.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedOffBottomAndTempRange.PARAM_minTemp)).getValueAsString());
        jtfMaxTemp.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedOffBottomAndTempRange.PARAM_maxTemp)).getValueAsString());
        jtfRPW.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedOffBottomAndTempRange.PARAM_rpw)).getValueAsString());
        jchkTempTakesPrecedence.setSelected((Boolean)obj.getParameter(VerticalMovement_FixedOffBottomAndTempRange.PARAM_TempTakesPrecedence).getValue());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfRPW = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMaxDepth = new javax.swing.JTextField();
        jtfMinDistOffBottom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfMinTemp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfMaxTemp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfMinDepth = new javax.swing.JTextField();
        jchkTempTakesPrecedence = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(280, 180));
        setMinimumSize(new java.awt.Dimension(280, 180));
        setPreferredSize(new java.awt.Dimension(280, 180));

        jLabel1.setText("random walk parameter (m^2/s)");
        jLabel1.setToolTipText("");

        jtfRPW.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfRPW.setText("0.0");
        jtfRPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRPWActionPerformed(evt);
            }
        });

        jLabel2.setText("min depth (m)");

        jtfMaxDepth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMaxDepth.setText("0");
        jtfMaxDepth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaxDepthActionPerformed(evt);
            }
        });

        jtfMinDistOffBottom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMinDistOffBottom.setText("0");
        jtfMinDistOffBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinDistOffBottomActionPerformed(evt);
            }
        });

        jLabel3.setText("max depth (m)");
        jLabel3.setToolTipText("");

        jLabel4.setText("min distance off bottom (m)");
        jLabel4.setToolTipText("");

        jtfMinTemp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMinTemp.setText("0");
        jtfMinTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinTempActionPerformed(evt);
            }
        });

        jLabel5.setText("min temperature (deg C)");

        jtfMaxTemp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMaxTemp.setText("0");
        jtfMaxTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaxTempActionPerformed(evt);
            }
        });

        jLabel6.setText("max temperature (deg C)");
        jLabel6.setToolTipText("");

        jtfMinDepth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMinDepth.setText("0");
        jtfMinDepth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinDepthActionPerformed(evt);
            }
        });

        jchkTempTakesPrecedence.setText("temp range takes precedence");
        jchkTempTakesPrecedence.setToolTipText("select if temp range takes precedence over depth range");
        jchkTempTakesPrecedence.setActionCommand("temp range takes priority");
        jchkTempTakesPrecedence.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchkTempTakesPrecedenceItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfRPW, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfMinDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfMaxDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfMinDistOffBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfMinTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtfMaxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
            .addComponent(jchkTempTakesPrecedence)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMinDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaxDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMinDistOffBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMinTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addComponent(jchkTempTakesPrecedence))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRPWActionPerformed
        String str = jtfRPW.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_rpw, val);
    }//GEN-LAST:event_jtfRPWActionPerformed

    private void jtfMinDepthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinDepthActionPerformed
        String str = jtfMinDepth.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_minDepth, val);
    }//GEN-LAST:event_jtfMinDepthActionPerformed

    private void jtfMaxDepthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaxDepthActionPerformed
        String str = jtfRPW.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_maxDepth, val);
    }//GEN-LAST:event_jtfMaxDepthActionPerformed

    private void jtfMinDistOffBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinDistOffBottomActionPerformed
        String str = jtfMinDistOffBottom.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_minDistOffBottom, val);
    }//GEN-LAST:event_jtfMinDistOffBottomActionPerformed

    private void jtfMinTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinTempActionPerformed
        String str = jtfMinTemp.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_minTemp, val);
    }//GEN-LAST:event_jtfMinTempActionPerformed

    private void jtfMaxTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaxTempActionPerformed
        String str = jtfMaxTemp.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_maxTemp, val);
    }//GEN-LAST:event_jtfMaxTempActionPerformed

    private void jchkTempTakesPrecedenceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchkTempTakesPrecedenceItemStateChanged
        boolean tempPrefd = jchkTempTakesPrecedence.isSelected();
        obj.setParameterValue(VerticalMovement_FixedDepthAndTempRange.PARAM_TempTakesPrecedence, tempPrefd);
    }//GEN-LAST:event_jchkTempTakesPrecedenceItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox jchkTempTakesPrecedence;
    private javax.swing.JTextField jtfMaxDepth;
    private javax.swing.JTextField jtfMaxTemp;
    private javax.swing.JTextField jtfMinDepth;
    private javax.swing.JTextField jtfMinDistOffBottom;
    private javax.swing.JTextField jtfMinTemp;
    private javax.swing.JTextField jtfRPW;
    // End of variables declaration//GEN-END:variables
}
