/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wts.models.DisMELS.IBMFunctions.Movement;

import wts.models.DisMELS.framework.IBMFunctions.IBMParameterDouble;

/**
 *
 * @author William.Stockhausen
 */
public class VerticalMovement_FixedDepthRangeCustomizer extends javax.swing.JPanel implements java.beans.Customizer {
    
    private VerticalMovement_FixedDepthRange obj = null;

    /**
     * Creates new customizer DielVerticalMigration_FixedDepthRangesCustomizer
     */
    public VerticalMovement_FixedDepthRangeCustomizer() {
        initComponents();
    }
    
    @Override
    public void setObject(Object bean) {
        if (bean instanceof VerticalMovement_FixedDepthRange){
            obj = (VerticalMovement_FixedDepthRange) bean;
            setParameters();
        }
    }

    private void setParameters() {
        jtfMinDepth.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthRange.PARAM_minDepth)).getValueAsString());
        jtfMaxDepth.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthRange.PARAM_maxDepth)).getValueAsString());
        jtfMinDistOffBottom.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthRange.PARAM_minDistOffBottom)).getValueAsString());
        jtfRPW.setText(((IBMParameterDouble)obj.getParameter(VerticalMovement_FixedDepthRange.PARAM_rpw)).getValueAsString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfRPW = new javax.swing.JTextField();
        jtfMinDepth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMaxDepth = new javax.swing.JTextField();
        jtfMinDistOffBottom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(305, 32767));
        setMinimumSize(new java.awt.Dimension(305, 0));
        setPreferredSize(new java.awt.Dimension(305, 122));

        jLabel1.setText("random walk parameter (m^2/s)");
        jLabel1.setToolTipText("");

        jtfRPW.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfRPW.setText("0.0");
        jtfRPW.setToolTipText("diffusion constant");
        jtfRPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRPWActionPerformed(evt);
            }
        });

        jtfMinDepth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMinDepth.setText("0");
        jtfMinDepth.setToolTipText("min preferred depth (in deep water)");
        jtfMinDepth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinDepthActionPerformed(evt);
            }
        });

        jLabel2.setText("nominal min depth (m)");

        jtfMaxDepth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMaxDepth.setText("1000");
        jtfMaxDepth.setToolTipText("max preferred depth (i.e., n deep water)");
        jtfMaxDepth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMaxDepthActionPerformed(evt);
            }
        });

        jtfMinDistOffBottom.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfMinDistOffBottom.setText("0");
        jtfMinDistOffBottom.setToolTipText("can't get closer to bottom than this");
        jtfMinDistOffBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinDistOffBottomActionPerformed(evt);
            }
        });

        jLabel3.setText("nominal max depth (m)");
        jLabel3.setToolTipText("");

        jLabel4.setText("min distance off bottom (m)");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfRPW, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfMinDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfMaxDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfMinDistOffBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMinDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMaxDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMinDistOffBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRPWActionPerformed
        String str = jtfRPW.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthRange.PARAM_rpw, val);
    }//GEN-LAST:event_jtfRPWActionPerformed

    private void jtfMinDepthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinDepthActionPerformed
        String str = jtfMinDepth.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthRange.PARAM_minDepth, val);
    }//GEN-LAST:event_jtfMinDepthActionPerformed

    private void jtfMaxDepthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMaxDepthActionPerformed
        String str = jtfRPW.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthRange.PARAM_maxDepth, val);
    }//GEN-LAST:event_jtfMaxDepthActionPerformed

    private void jtfMinDistOffBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinDistOffBottomActionPerformed
        String str = jtfMinDistOffBottom.getText();
        Double val = Double.parseDouble(str);
        obj.setParameterValue(VerticalMovement_FixedDepthRange.PARAM_minDistOffBottom, val);
    }//GEN-LAST:event_jtfMinDistOffBottomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfMaxDepth;
    private javax.swing.JTextField jtfMinDepth;
    private javax.swing.JTextField jtfMinDistOffBottom;
    private javax.swing.JTextField jtfRPW;
    // End of variables declaration//GEN-END:variables
}
