/*
 * JSpinnerBean.java
 *
 * Created on March 7, 2003, 3:26 PM
 *
 *  Provides a shell to act as a Sun ONE Studio visual component
 *
 */

package com.wtstockhausen.beans.swing;

/**
 *
 * @author  William Stockhausen
 */
public class JSpinnerBean extends javax.swing.JSpinner {
    
    /** Creates new form BeanForm */
    public JSpinnerBean() {
        super();
        initComponents();
    }
    
    public JSpinnerBean(javax.swing.SpinnerModel sm) {
        super(sm);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
