/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wts.models.DisMELS.IBMFunctions.HSMs;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import wts.models.DisMELS.framework.GlobalInfo;
import wts.models.DisMELS.framework.IBMFunctions.IBMParameterString;

/**
 *
 * @author william.stockhausen
 */
public class HSMFunction_NetCDFCustomizer extends javax.swing.JPanel implements java.beans.Customizer {

    private HSMFunction_NetCDF obj = null;
    private JFileChooser jfc = new JFileChooser();
    
    /**
     * Creates new form HSMFunction_NetCDFCustomizer
     */
    public HSMFunction_NetCDFCustomizer() {
        initComponents();
        FileFilter ff = new FileNameExtensionFilter("netCDF files", "nc");
        jfc.setFileFilter(ff);
        jfc.setDialogTitle("path to a Habitat Suitability Map in netCDF format");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfFilename = new javax.swing.JTextField();
        jbFindFile = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(HSMFunction_NetCDFCustomizer.class, "HSMFunction_NetCDFCustomizer.jPanel1.border.title"))); // NOI18N

        jtfFilename.setText(org.openide.util.NbBundle.getMessage(HSMFunction_NetCDFCustomizer.class, "HSMFunction_NetCDFCustomizer.jtfFilename.text")); // NOI18N
        jtfFilename.setToolTipText(org.openide.util.NbBundle.getMessage(HSMFunction_NetCDFCustomizer.class, "HSMFunction_NetCDFCustomizer.jtfFilename.toolTipText")); // NOI18N
        jtfFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFilenameActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jbFindFile, org.openide.util.NbBundle.getMessage(HSMFunction_NetCDFCustomizer.class, "HSMFunction_NetCDFCustomizer.jbFindFile.text")); // NOI18N
        jbFindFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFindFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jtfFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFindFile))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jtfFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbFindFile))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFilenameActionPerformed
       String fn = jtfFilename.getText();
       File f = new File(fn);
       if (f.exists()) {
           jfc.setSelectedFile(f);
       } else {
           JOptionPane.showMessageDialog(jPanel1, "File '"+fn+"' does not exist.","File not found error",JOptionPane.ERROR_MESSAGE);
           String fnp = jfc.getSelectedFile().getPath();
           f = new File(fnp);
           if (f.exists()) {
               jtfFilename.setText(fnp);//revert to previous file
               obj.setParameterValue(HSMFunction_NetCDF.PARAM_fileName, fnp);
           } else {
               jtfFilename.setText("");
           }
       }
    }//GEN-LAST:event_jtfFilenameActionPerformed

    private void jbFindFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFindFileActionPerformed
        if (jfc.showOpenDialog(jPanel1)==JFileChooser.APPROVE_OPTION){
           File f = jfc.getSelectedFile();
           String fn = f.getPath();
           jtfFilename.setText(fn);
           obj.setParameterValue(HSMFunction_NetCDF.PARAM_fileName, fn);
        }
    }//GEN-LAST:event_jbFindFileActionPerformed

    @Override
    public void setObject(Object bean) {
        if (bean instanceof HSMFunction_NetCDF){
            obj = (HSMFunction_NetCDF) bean;
            setParameters();
        }
    }

    private void setParameters() {
        String fn = ((IBMParameterString)obj.getParameter(HSMFunction_NetCDF.PARAM_fileName)).getValueAsString();
        jtfFilename.setText(fn);
        File f = new File(fn);
        if (f.exists()){
            jfc.setSelectedFile(f);
        } else {
            File d = new File(GlobalInfo.getInstance().getWorkingDir());
            if (d.exists()) jfc.setCurrentDirectory(d);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbFindFile;
    private javax.swing.JTextField jtfFilename;
    // End of variables declaration//GEN-END:variables
}
