/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wts.models.DisMELS.topcomponents;

import java.beans.ExceptionListener;
import java.io.File;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import wts.models.DisMELS.framework.GlobalInfo;
import wts.models.DisMELS.topcomponents.LHSParametersEditor.LHSParametersEditorTopComponent;
import wts.models.DisMELS.topcomponents.LHSAttributesEditor.LHSAttributesEditorTopComponent;
import wts.models.DisMELS.topcomponents.LHSTypesEditor.LHSTypesEditorTopComponent;
import wts.models.DisMELS.topcomponents.ModelReviewer.ModelReviewerTopComponent;
import wts.models.DisMELS.topcomponents.ModelRunner.ModelRunnerTopComponent;
import wts.roms.topcomponents.ROMSInfoEditor.ROMSInfoEditorTopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//wts.models.DisMELS.topcomponents//ModelCoordinator//EN",
autostore = false)
@TopComponent.Description(preferredID = "ModelCoordinatorTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "wts.models.DisMELS.topcomponents.ModelCoordinatorTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_ModelCoordinatorAction",
preferredID = "ModelCoordinatorTopComponent")
@Messages({
    "CTL_ModelCoordinatorAction=Model coordinator",
    "CTL_ModelCoordinatorTopComponent=Model Coordinator",
    "HINT_ModelCoordinatorTopComponent=This is the Model Coordinator window"
})
public final class ModelCoordinatorTopComponent extends TopComponent 
                                                implements ExceptionListener  {
    
    /** */
    private static Logger logger = Logger.getLogger(ModelCoordinatorTopComponent.class.getName());
    
    /** file chooser for working directory */
    private JFileChooser jfc  = new JFileChooser();

    public ModelCoordinatorTopComponent() {
        initComponents();
        setName(Bundle.CTL_ModelCoordinatorTopComponent());
        setToolTipText(Bundle.HINT_ModelCoordinatorTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbtnSetPluginsDir = new javax.swing.JButton();
        jchkSetPluginsDir = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbtnSetWorkingDir = new javax.swing.JButton();
        jchkSetWorkingDir = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbtnSetROMSInfo = new javax.swing.JButton();
        jchkSetROMSInfo = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbtnDefineLHSTypes = new javax.swing.JButton();
        jchkDefineLHSTypes = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbtnDefineLHSParameterValues = new javax.swing.JButton();
        jchkDefineLHSParameterValues = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jbtnDefineInitialAttributes = new javax.swing.JButton();
        jchkDefineInitialAttributes = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jbtnRunDisMELS = new javax.swing.JButton();
        jchkRunDisMELS = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jbtnReviewModel = new javax.swing.JButton();
        jchkReviewModel = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jtfWorkingDir = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnSetPluginsDir, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnSetPluginsDir.text")); // NOI18N
        jbtnSetPluginsDir.setActionCommand(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnSetPluginsDir.actionCommand")); // NOI18N
        jbtnSetPluginsDir.setEnabled(false);
        jbtnSetPluginsDir.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnSetPluginsDir.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnSetPluginsDir.setPreferredSize(new java.awt.Dimension(243, 25));

        org.openide.awt.Mnemonics.setLocalizedText(jchkSetPluginsDir, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkSetPluginsDir.text")); // NOI18N
        jchkSetPluginsDir.setEnabled(false);
        jchkSetPluginsDir.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkSetPluginsDir)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSetPluginsDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkSetPluginsDir, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jbtnSetPluginsDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnSetWorkingDir, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnSetWorkingDir.text")); // NOI18N
        jbtnSetWorkingDir.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnSetWorkingDir.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnSetWorkingDir.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnSetWorkingDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSetWorkingDirActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkSetWorkingDir, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkSetWorkingDir.text")); // NOI18N
        jchkSetWorkingDir.setEnabled(false);
        jchkSetWorkingDir.setFocusable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkSetWorkingDir)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSetWorkingDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkSetWorkingDir, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jbtnSetWorkingDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel4.text")); // NOI18N
        jLabel4.setToolTipText(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel4.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnSetROMSInfo, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnSetROMSInfo.text")); // NOI18N
        jbtnSetROMSInfo.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnSetROMSInfo.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnSetROMSInfo.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnSetROMSInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSetROMSInfoActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkSetROMSInfo, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkSetROMSInfo.text")); // NOI18N
        jchkSetROMSInfo.setEnabled(false);
        jchkSetROMSInfo.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkSetROMSInfo)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSetROMSInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkSetROMSInfo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jbtnSetROMSInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel6.text")); // NOI18N
        jLabel6.setToolTipText(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel6.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnDefineLHSTypes, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnDefineLHSTypes.text")); // NOI18N
        jbtnDefineLHSTypes.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnDefineLHSTypes.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnDefineLHSTypes.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnDefineLHSTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDefineLHSTypesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkDefineLHSTypes, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkDefineLHSTypes.text")); // NOI18N
        jchkDefineLHSTypes.setEnabled(false);
        jchkDefineLHSTypes.setFocusable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkDefineLHSTypes)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDefineLHSTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkDefineLHSTypes, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jbtnDefineLHSTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnDefineLHSParameterValues, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnDefineLHSParameterValues.text")); // NOI18N
        jbtnDefineLHSParameterValues.setActionCommand(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnDefineLHSParameterValues.actionCommand")); // NOI18N
        jbtnDefineLHSParameterValues.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnDefineLHSParameterValues.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnDefineLHSParameterValues.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnDefineLHSParameterValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDefineLHSParameterValuesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkDefineLHSParameterValues, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkDefineLHSParameterValues.text")); // NOI18N
        jchkDefineLHSParameterValues.setEnabled(false);
        jchkDefineLHSParameterValues.setFocusable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkDefineLHSParameterValues)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDefineLHSParameterValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkDefineLHSParameterValues, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jbtnDefineLHSParameterValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnDefineInitialAttributes, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnDefineInitialAttributes.text")); // NOI18N
        jbtnDefineInitialAttributes.setActionCommand(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnDefineInitialAttributes.actionCommand")); // NOI18N
        jbtnDefineInitialAttributes.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnDefineInitialAttributes.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnDefineInitialAttributes.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnDefineInitialAttributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDefineInitialAttributesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkDefineInitialAttributes, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkDefineInitialAttributes.text")); // NOI18N
        jchkDefineInitialAttributes.setEnabled(false);
        jchkDefineInitialAttributes.setFocusable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkDefineInitialAttributes)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDefineInitialAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkDefineInitialAttributes, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jbtnDefineInitialAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnRunDisMELS, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnRunDisMELS.text")); // NOI18N
        jbtnRunDisMELS.setActionCommand(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnRunDisMELS.actionCommand")); // NOI18N
        jbtnRunDisMELS.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnRunDisMELS.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnRunDisMELS.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnRunDisMELS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRunDisMELSActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkRunDisMELS, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkRunDisMELS.text")); // NOI18N
        jchkRunDisMELS.setEnabled(false);
        jchkRunDisMELS.setFocusable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkRunDisMELS)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRunDisMELS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkRunDisMELS, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jbtnRunDisMELS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jbtnReviewModel, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnReviewModel.text")); // NOI18N
        jbtnReviewModel.setActionCommand(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jbtnReviewModel.actionCommand")); // NOI18N
        jbtnReviewModel.setMaximumSize(new java.awt.Dimension(243, 25));
        jbtnReviewModel.setMinimumSize(new java.awt.Dimension(243, 25));
        jbtnReviewModel.setPreferredSize(new java.awt.Dimension(243, 25));
        jbtnReviewModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReviewModelActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jchkReviewModel, org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jchkReviewModel.text")); // NOI18N
        jchkReviewModel.setEnabled(false);
        jchkReviewModel.setFocusable(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkReviewModel)
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnReviewModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jchkReviewModel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(jbtnReviewModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jPanel12.border.title"))); // NOI18N

        jtfWorkingDir.setEditable(false);
        jtfWorkingDir.setText(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jtfWorkingDir.text")); // NOI18N
        jtfWorkingDir.setToolTipText(org.openide.util.NbBundle.getMessage(ModelCoordinatorTopComponent.class, "ModelCoordinatorTopComponent.jtfWorkingDir.toolTipText")); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfWorkingDir, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfWorkingDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(164, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSetROMSInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSetROMSInfoActionPerformed
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {
            public void run() {
                TopComponent win = ROMSInfoEditorTopComponent.findInstance();
                win.open();
                win.requestActive();
            }
        });
    }//GEN-LAST:event_jbtnSetROMSInfoActionPerformed

    private void jbtnSetWorkingDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSetWorkingDirActionPerformed
        int res = jfc.showOpenDialog(null);
        if (res==jfc.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            String wd = f.getPath()+File.separator;//close path
            GlobalInfo.getInstance().setWorkingDir(wd);
            logger.info("Working Directory set to "+wd);
            jchkSetWorkingDir.setSelected(true);
            jtfWorkingDir.setText(wd);
            jtfWorkingDir.setToolTipText(wd);
        }

    }//GEN-LAST:event_jbtnSetWorkingDirActionPerformed

    private void jbtnDefineLHSTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDefineLHSTypesActionPerformed
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {
            public void run() {
                TopComponent win = LHSTypesEditorTopComponent.findInstance();
                win.open();
                win.requestActive();
            }
        });
    }//GEN-LAST:event_jbtnDefineLHSTypesActionPerformed

    private void jbtnDefineLHSParameterValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDefineLHSParameterValuesActionPerformed
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {
            public void run() {
                TopComponent win = LHSParametersEditorTopComponent.findInstance();
                win.open();
                win.requestActive();
            }
        });
    }//GEN-LAST:event_jbtnDefineLHSParameterValuesActionPerformed

    private void jbtnDefineInitialAttributesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDefineInitialAttributesActionPerformed
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {
            public void run() {
                TopComponent win = LHSAttributesEditorTopComponent.findInstance();
                win.open();
                win.requestActive();
            }
        });
    }//GEN-LAST:event_jbtnDefineInitialAttributesActionPerformed

    private void jbtnRunDisMELSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRunDisMELSActionPerformed
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {
            public void run() {
                TopComponent win = ModelRunnerTopComponent.findInstance();
                win.open();
                win.requestActive();
            }
        });
    }//GEN-LAST:event_jbtnRunDisMELSActionPerformed

    private void jbtnReviewModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReviewModelActionPerformed
        WindowManager.getDefault().invokeWhenUIReady(new Runnable() {
            public void run() {
                TopComponent win = ModelReviewerTopComponent.findInstance();
                win.open();
                win.requestActive();
            }
        });
    }//GEN-LAST:event_jbtnReviewModelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtnDefineInitialAttributes;
    private javax.swing.JButton jbtnDefineLHSParameterValues;
    private javax.swing.JButton jbtnDefineLHSTypes;
    private javax.swing.JButton jbtnReviewModel;
    private javax.swing.JButton jbtnRunDisMELS;
    private javax.swing.JButton jbtnSetPluginsDir;
    private javax.swing.JButton jbtnSetROMSInfo;
    private javax.swing.JButton jbtnSetWorkingDir;
    private javax.swing.JCheckBox jchkDefineInitialAttributes;
    private javax.swing.JCheckBox jchkDefineLHSParameterValues;
    private javax.swing.JCheckBox jchkDefineLHSTypes;
    private javax.swing.JCheckBox jchkReviewModel;
    private javax.swing.JCheckBox jchkRunDisMELS;
    private javax.swing.JCheckBox jchkSetPluginsDir;
    private javax.swing.JCheckBox jchkSetROMSInfo;
    private javax.swing.JCheckBox jchkSetWorkingDir;
    private javax.swing.JTextField jtfWorkingDir;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        logger.info("-----starting compnonentOpened()");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Select working directory:");
        jfc.setApproveButtonText("Select");
        String wd = GlobalInfo.getInstance().getWorkingDir();
        if (!wd.equalsIgnoreCase("<not set>")){
            File f = new File(wd);
            jfc.setCurrentDirectory(f);
        }
        logger.info("-----ending compnonentOpened()");
    }

    @Override
    public void componentClosed() {
        logger.info("-----starting compnonentClosed()");
        logger.info("-----ending compnonentClosed()");
    }

    @Override
    public void exceptionThrown(Exception e) {
        logger.info(e.toString());
    }

    void writeProperties(java.util.Properties p) {
        logger.info("---starting ModelCoordinator.writeProperties()");
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        //store settings for GlobalInfo object
//        globalInfo = GlobalInfo.getInstance();
//        globalInfo.writeProperties(p);
        logger.info("---ending ModelCoordinator.writeProperties()");
    }

    /**
     * Read properties.
     * 
     * @param p 
     */
    void readProperties(java.util.Properties p) {
        logger.info("---starting readProperties()");
        //get version
        String version = p.getProperty("version");
        
        //read property settings for GlobalInfo object
//        globalInfo = GlobalInfo.getInstance();
//        globalInfo.readProperties(p);
        
        //check ROMS info
        String g = GlobalInfo.getInstance().getGridFile();
        if (!g.equals(GlobalInfo.PROP_NotSet)){
            jchkSetROMSInfo.setSelected(true);
        }
        
        //check working directory
        String wd = GlobalInfo.getInstance().getWorkingDir();
        jtfWorkingDir.setText(wd);
        if (!wd.equals(GlobalInfo.PROP_NotSet)){
            jchkSetWorkingDir.setSelected(true);
            jtfWorkingDir.setToolTipText(wd);
        }
        
        logger.info("---finished readProperties()");
    }
}
