/*
 * CoordinateSystemCreatorGUI.java
 *
 * Created on June 15, 2006, 4:15 PM
 */

package wts.GIS.cs;

import org.geotools.cs.CoordinateSystem;

/**
 *
 * @author  William Stockhausen
 */
public class CoordinateSystemCreatorGUI extends javax.swing.JFrame {
    
    CoordinateSystemCreator creator;
    
    /**
     * Creates new form CoordinateSystemCreatorGUI
     */
    public CoordinateSystemCreatorGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jtfEPSG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaWKT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jtfEPSG.setText("epsg code");
        jtfEPSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEPSGActionPerformed(evt);
            }
        });

        jtaWKT.setColumns(20);
        jtaWKT.setRows(5);
        jScrollPane1.setViewportView(jtaWKT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(jtfEPSG, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jtfEPSG, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEPSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEPSGActionPerformed
        String epsg = jtfEPSG.getText();
        jtaWKT.setText("");
        try {
            CoordinateSystem cs = CoordinateSystemCreator.createCoordinateSystem(epsg);
            String str = cs.toWKT();
            jtaWKT.setText(str);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jtfEPSGActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoordinateSystemCreatorGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaWKT;
    private javax.swing.JTextField jtfEPSG;
    // End of variables declaration//GEN-END:variables
    
}
