/*
 * JPanel_Axis.java
 *
 * Created on December 8, 2005, 6:32 PM
 */

package wts.roms.gui;

import wts.roms.*;
import wts.roms.ui.events.StateChangedSupport;
import java.awt.Component;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  William Stockhausen
 */
public class JPanel_Axis extends javax.swing.JPanel {
    
    private StateChangedSupport scSupport;
    
    /**
     * Creates new form JPanel_Axis
     */
    public JPanel_Axis() {
        scSupport = new StateChangedSupport(this);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jpSettings = new javax.swing.JPanel();
        jtfName = new javax.swing.JTextField();
        jspStart = new javax.swing.JSpinner();
        jspEnd = new javax.swing.JSpinner();
        jpXY = new javax.swing.JPanel();
        jrbX = new javax.swing.JRadioButton();
        jrbY = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(300, 20));
        setPreferredSize(new java.awt.Dimension(500, 40));
        jpSettings.setPreferredSize(new java.awt.Dimension(10, 20));
        jtfName.setEditable(false);
        jtfName.setText("Dim Name");
        jtfName.setEnabled(false);

        jspStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspStartStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpSettingsLayout = new org.jdesktop.layout.GroupLayout(jpSettings);
        jpSettings.setLayout(jpSettingsLayout);
        jpSettingsLayout.setHorizontalGroup(
            jpSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jpSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jtfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(15, 15, 15)
                .add(jspStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(jspEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSettingsLayout.setVerticalGroup(
            jpSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.BASELINE, jtfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(org.jdesktop.layout.GroupLayout.BASELINE, jspStart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(org.jdesktop.layout.GroupLayout.BASELINE, jspEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jrbX.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbX.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrbX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbXActionPerformed(evt);
            }
        });

        jrbY.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbY.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrbY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbYActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpXYLayout = new org.jdesktop.layout.GroupLayout(jpXY);
        jpXY.setLayout(jpXYLayout);
        jpXYLayout.setHorizontalGroup(
            jpXYLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jpXYLayout.createSequentialGroup()
                .addContainerGap()
                .add(jrbX)
                .add(17, 17, 17)
                .add(jrbY)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpXYLayout.setVerticalGroup(
            jpXYLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.BASELINE, jrbX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(org.jdesktop.layout.GroupLayout.BASELINE, jrbY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jpSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 396, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpXY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jpXY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbYActionPerformed
        scSupport.fireStateChangedEvent(jrbY);
    }//GEN-LAST:event_jrbYActionPerformed

    private void jrbXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbXActionPerformed
        scSupport.fireStateChangedEvent(jrbX);
    }//GEN-LAST:event_jrbXActionPerformed

    private void jspStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspStartStateChanged
        scSupport.fireStateChangedEvent(jspStart);
    }//GEN-LAST:event_jspStartStateChanged
    
    public void enableSingleSpinner(boolean b) {
        jspEnd.setEnabled(b);
    }
    
    public String getAxisName() {
        return jtfName.getText();
    }
    
    public void setAxisName(String name) {
        jtfName.setText(name);
    }
    
    public boolean isSelectedX() {
        return jrbX.isSelected();
    }
    
    public void setSelectedX(boolean b) {
        jrbX.setSelected(b);
    }
    
    public boolean isSelectedY() {
        return jrbY.isSelected();
    }
    
    public void setSelectedY(boolean b) {
        jrbY.setSelected(b);
    }
    
    public int[] getRange() {
        int[] r = new int[2];
        r[0] = ((Integer) jspStart.getValue()).intValue();
        r[1] = ((Integer) jspEnd.getValue()).intValue();
        return r;
    }
    
    public void setSpinnerModel(SpinnerNumberModel sm) {
        SpinnerNumberModel sm1 = new SpinnerNumberModel((Integer)sm.getMaximum(),
                                                        (Integer)sm.getMinimum(),
                                                        (Integer)sm.getMaximum(),
                                                        (Integer)sm.getStepSize());
        jspStart.setModel(sm);
        jspEnd.setModel(sm1);
    }
    
    public void removeXY() {
        this.remove(jpXY);
        this.invalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpSettings;
    private javax.swing.JPanel jpXY;
    private javax.swing.JRadioButton jrbX;
    private javax.swing.JRadioButton jrbY;
    private javax.swing.JSpinner jspEnd;
    private javax.swing.JSpinner jspStart;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
    
}
