/*
 * JPanel_Axes.java
 *
 * Created on December 9, 2005, 2:11 PM
 */

package wts.roms.gui;

import wts.roms.*;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;
import wts.roms.model.ModelData;

/**
 *
 * @author  William Stockhausen
 */
public class JPanel_Axes extends javax.swing.JPanel {
    
    ArrayList axlist;
    ModelData md;
    
    /** Creates new form JPanel_Axes */
    public JPanel_Axes() {
        axlist = new ArrayList();
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jpLabels = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpXYLabels = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpAxes = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createTitledBorder("Axes"));
        jpLabels.setOpaque(false);
        jpLabels.setPreferredSize(new java.awt.Dimension(10, 20));
        jLabel1.setText("Name");

        jLabel4.setText("Start");

        jLabel5.setText("End");

        org.jdesktop.layout.GroupLayout jpLabelsLayout = new org.jdesktop.layout.GroupLayout(jpLabels);
        jpLabels.setLayout(jpLabelsLayout);
        jpLabelsLayout.setHorizontalGroup(
            jpLabelsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpLabelsLayout.createSequentialGroup()
                .add(48, 48, 48)
                .add(jLabel1)
                .add(126, 126, 126)
                .add(jLabel4)
                .add(93, 93, 93)
                .add(jLabel5)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jpLabelsLayout.setVerticalGroup(
            jpLabelsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jpLabelsLayout.createSequentialGroup()
                .add(jpLabelsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel4)
                    .add(jLabel1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("X");

        jLabel3.setText("Y");

        org.jdesktop.layout.GroupLayout jpXYLabelsLayout = new org.jdesktop.layout.GroupLayout(jpXYLabels);
        jpXYLabels.setLayout(jpXYLabelsLayout);
        jpXYLabelsLayout.setHorizontalGroup(
            jpXYLabelsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jpXYLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(22, 22, 22)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpXYLabelsLayout.setVerticalGroup(
            jpXYLabelsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jpXYLabelsLayout.createSequentialGroup()
                .add(jpXYLabelsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                .add(jpLabels, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 386, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpXYLabels, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpLabels, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jpXYLabels, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        add(jPanel2, java.awt.BorderLayout.NORTH);

        jpAxes.setLayout(new javax.swing.BoxLayout(jpAxes, javax.swing.BoxLayout.Y_AXIS));

        add(jpAxes, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    public void addAxis(String name, SpinnerNumberModel sm) {
        JPanel_Axis ax = new JPanel_Axis();
        ax.setAxisName(name);
        ax.setSpinnerModel(sm);
        jpAxes.add(ax);
        jpAxes.revalidate();
    }
    
    public void setModelData(ModelData md) {
        this.md = md;
        int r        = md.getRank();
        int[] shp    = md.getShape();
        String[] str = md.getDimNames();
        for (int i=0;i<r;i++) {
            String name = str[i];
            Integer mn = new Integer(0);
            Integer mx = new Integer(shp[i]-1);
            Integer ic = new Integer(1);
            Integer vl = new Integer(0);
            SpinnerNumberModel sm = new SpinnerNumberModel(vl,mn,mx,ic);
            addAxis(name,sm);
        }        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpAxes;
    private javax.swing.JPanel jpLabels;
    private javax.swing.JPanel jpXYLabels;
    // End of variables declaration//GEN-END:variables
    
}
