/*
 * JPanel_NetcdfReader.java
 *
 * Created on December 8, 2005, 10:04 PM
 */

package wts.roms.gui;

import wts.roms.model.NetcdfReader;
import wts.roms.ui.events.StateChangedEventListener;
import wts.roms.ui.events.StateChangedSupport;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ucar.nc2.dataset.NetcdfDataset;

/**
 *
 * @author  William Stockhausen
 */
public class JPanel_NetcdfReader extends javax.swing.JPanel {
    
    private JFileChooser jFC;
    private NetcdfReader netcdfReader;
    private StateChangedSupport scSupport;
    
    /**
     * Creates new form JPanel_NetcdfReader
     */
    public JPanel_NetcdfReader() {
        scSupport = new StateChangedSupport(this);
        initComponents();
        jFC = new JFileChooser();
        jFC.setCurrentDirectory(new java.io.File("D:/MyDocuments/Projects/ROMS/ModelData/NEP_Grid"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jcbDataset = new javax.swing.JComboBox();
        jbSelect = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Netcdf dataset"));
        jcbDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDatasetActionPerformed(evt);
            }
        });

        jbSelect.setText("Select");
        jbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                .add(jcbDataset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 314, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                .add(jbSelect))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jcbDataset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jbSelect))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 405, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 60, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectActionPerformed
        int res = jFC.showOpenDialog(this);
        if (res==JFileChooser.APPROVE_OPTION) {
            String dsn = jFC.getSelectedFile().getPath();
            jcbDataset.addItem(dsn);
            jcbDataset.setSelectedItem(dsn);
            openDataset(dsn);
        }
    }//GEN-LAST:event_jbSelectActionPerformed

        private void jcbDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDatasetActionPerformed
            String dsn = (String) jcbDataset.getSelectedItem();
            openDataset(dsn);
        }//GEN-LAST:event_jcbDatasetActionPerformed

    public void addStateChangedEventListener(StateChangedEventListener el) {
        scSupport.addStateChangedEventListener(el);
    }
    
    public void removeStateChangedEventListener(StateChangedEventListener el) {
        scSupport.removeStateChangedEventListener(el);
    }
    
    private void openDataset(String dsn) {
        try {
            netcdfReader = new NetcdfReader(dsn);
            
        } catch (java.io.IOException ex) {
            JOptionPane d = new JOptionPane();
            d.showMessageDialog(null,"Not a netCDF file",
                                     "File selection",
                                     JOptionPane.ERROR_MESSAGE);
            return;
        }
        scSupport.fireStateChangedEvent();
    }
    
    public NetcdfReader getNetcdfReader() {
        return netcdfReader;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbSelect;
    private javax.swing.JComboBox jcbDataset;
    // End of variables declaration//GEN-END:variables
    
}
